-- Hibernate auto-created

-- Customer + Address + Contact stored together
create table public.customers
(
    id                                    bigint generated by default as identity
        primary key,
    address_line1                         varchar(255),
    address_line2                         varchar(255),
    city                                  varchar(255),
    country                               varchar(255),
    postal_code                           varchar(255),
    state                                 varchar(255),
    agreement_link                        varchar(255),
    amount_of_gallons_for_last_two_months bigint,
    balance                               numeric(38, 2),
    contact_name                          varchar(255),
    email                                 varchar(255),
    phone                                 varchar(255),
    current_month_gallons                 bigint,
    discount                              numeric(38, 2),
    forecasted_fuel_amount                bigint,
    forecasted_rebate                     numeric(38, 2),
    name                                  varchar(255),
    payment_link                          varchar(255),
    rebate_as_credit                      boolean,
    status                                varchar(255)
        constraint customers_status_check
            check ((status)::text = ANY ((ARRAY ['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[]))
);

alter table public.customers
    owner to postgres;

create table public.fuel_stations
(
    id            bigint generated by default as identity
        primary key,
    address_line1 varchar(255),
    address_line2 varchar(255),
    city          varchar(255),
    country       varchar(255),
    latitude      varchar(255),
    longitude     varchar(255),
    name          varchar(255),
    postal_code   varchar(255),
    state         varchar(255)
);

alter table public.fuel_stations
    owner to postgres;

create table public.payments
(
    id          bigint generated by default as identity
        primary key,
    amount      numeric(38, 2),
    currency    varchar(255)
        constraint payments_currency_check
            check ((currency)::text = ANY ((ARRAY ['CAD'::character varying, 'USD'::character varying])::text[])),
    datetime    bigint,
    method      varchar(255),
    status      varchar(255)
        constraint payments_status_check
            check ((status)::text = ANY
                   ((ARRAY ['PENDING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying, 'REFUNDED'::character varying])::text[])),
    type        varchar(255)
        constraint payments_type_check
            check ((type)::text = ANY
                   ((ARRAY ['PAYMENT'::character varying, 'DEPOSIT'::character varying, 'REFUND'::character varying, 'REBATE'::character varying, 'ACCOUNT_TOP_UP'::character varying])::text[])),
    customer_id bigint
        constraint fk45dp0030s8e3myd8n6ky4e79g
            references public.customers
);

alter table public.payments
    owner to postgres;

create table public.purchase_orders
(
    id              bigint generated by default as identity
        primary key,
    cards_quantity  integer,
    address_line1   varchar(255),
    address_line2   varchar(255),
    city            varchar(255),
    country         varchar(255),
    postal_code     varchar(255),
    state           varchar(255),
    contact_name    varchar(255),
    email           varchar(255),
    phone           varchar(255),
    shipping_method varchar(255),
    status          varchar(255)
        constraint purchase_orders_status_check
            check ((status)::text = ANY
                   ((ARRAY ['NEW'::character varying, 'SHIPPED'::character varying, 'COMPLETED'::character varying])::text[])),
    tracking_number varchar(255),
    customer_id     bigint
        constraint fkfbqmektiojpqhypnpog4uqk41
            references public.customers
);

alter table public.purchase_orders
    owner to postgres;

create table public.fuel_cards
(
    id          bigint generated by default as identity
        primary key,
    card_number varchar(255),
    email       varchar(255),
    full_name   varchar(255),
    pin         varchar(255),
    provider    varchar(255)
        constraint fuel_cards_provider_check
            check ((provider)::text = ANY
                   ((ARRAY ['EFS'::character varying, 'Comdata'::character varying, 'BVD_PETROLEUM'::character varying])::text[])),
    status      varchar(255)
        constraint fuel_cards_status_check
            check ((status)::text = ANY
                   ((ARRAY ['ACTIVE'::character varying, 'INACTIVE'::character varying, 'DELETED'::character varying])::text[])),
    customer_id bigint
        constraint fkm1ttunb0ljg5l001mympto560
            references public.customers,
    order_id    bigint
        constraint fkinn1xog9fody0bp54t0228c8g
            references public.purchase_orders
);

alter table public.fuel_cards
    owner to postgres;

create table public.fuel_card_transactions
(
    id                 bigint generated by default as identity
        primary key,
    datetime           bigint,
    ref_transaction_id varchar(255),
    tax                numeric(38, 2),
    total_amount       numeric(38, 2),
    card_id            bigint
        constraint fkdim81di7oup8hb59aijprk3xs
            references public.fuel_cards,
    customer_id        bigint
        constraint fk1gkh0uicp6hqnmf95oepshn9o
            references public.customers,
    station_id         bigint
        constraint fkik1stxv728u5xt67f505yfgsa
            references public.fuel_stations
);

alter table public.fuel_card_transactions
    owner to postgres;

create table public.fuel_card_transaction_lines
(
    id              bigint generated by default as identity
        primary key,
    category        varchar(255)
        constraint fuel_card_transaction_lines_category_check
            check ((category)::text = ANY
                   ((ARRAY ['TRACTOR_FUEL'::character varying, 'OTHER_FUEL'::character varying, 'OTHER_PRODUCT'::character varying])::text[])),
    discount_amount numeric(38, 2),
    price_per_unit  numeric(38, 2),
    quantity        numeric(38, 2),
    tax             numeric(38, 2),
    type            varchar(255)
        constraint fuel_card_transaction_lines_type_check
            check ((type)::text = ANY ((ARRAY ['FUEL'::character varying, 'NON_FUEL'::character varying])::text[])),
    transaction_id  bigint
        constraint fkqu9swshd44b5ymhvqox3ntg9n
            references public.fuel_card_transactions
);

alter table public.fuel_card_transaction_lines
    owner to postgres;

